# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: José Jaime Castellanos García
title: Data Scientist
email: castellanosgjj@gmail.com
website: https://github.com/castellanosjj

# Social links
twitter_username: KatouDeep
github_username:  castellanosjj
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: katou_deep
linkedin_username: castellanosjj
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jaime and I'm a Data Scientist. As well as sales engineer I also have experience on business development & technical presales for AI-based solutions. I've been using different programming languages like:

    - R
    - Python
    - SQL
    - UNIX (Bash)

  I am most skilled in: <mark>Google Cloud</mark> , <mark>Microsoft Azure</mark> , <mark>AWS</mark> & <mark>Alibaba Cloud</mark> .
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in artificial intelligence and machine learning some of my other interests and hobbies are:
   - Playing bass
   - Traveling
   - Gaming
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
